# Generated by Django 4.2.7 on 2024-01-29 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.reservation'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.reservation'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
