# Generated by Django 4.2.7 on 2024-01-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_order_customer_alter_feedback_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
