# Generated by Django 4.2.7 on 2024-01-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_delete_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
